# Generated by Django 6.1 on 2026-08-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('chocolate', 'Chocolate Glaseado'), ('fresa', 'Fresa con Chispas'), ('arequipe', 'Manjar / Arequipe'), ('clasica', 'Clásica de Azúcar')], max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
